name: revver
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.2+2

environment:
    sdk: ">=2.11.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 1.0.2
  indonesia: 1.0.1
  http: 0.13.5
  dio: 4.0.6
  flutter_html: 3.0.0-alpha.3
  shared_preferences: 2.0.15
  keyboard_dismisser: 2.0.0
  go_router: 3.1.1
  dropdown_search: 3.0.1
  cached_network_image: 3.2.0
  flutter_svg: 1.0.3
  salomon_bottom_bar: 3.3.1
  syncfusion_flutter_calendar: 19.4.56
  syncfusion_flutter_datagrid: 19.4.56
  syncfusion_flutter_pdfviewer: 19.4.56-beta
  syncfusion_flutter_gauges: 19.4.56
  advance_pdf_viewer: 2.0.1
  smooth_page_indicator: 1.0.0
  image_picker: 0.8.4
  url_launcher: 6.0.10
  chewie: 1.0.0
  video_player: 2.2.3
  webview_flutter: 2.0.13
  flutter_speed_dial: 6.2.0
  expandable: 5.0.1
  flutter_cart: 0.0.7
  midtrans_sdk: 0.3.4
  firebase_core: 2.4.1
  firebase_messaging: 14.2.1
  overlay_support: 1.2.1
  flutter_slidable: 1.3.2
  flutter_launcher_icons: 0.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/svg/
    - assets/img/
    - assets/pdf/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-Regular.ttf
    
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Regular.ttf

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/img/revver-icon.png"