name: revver
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
    sdk: ">=2.11.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 1.0.2
  indonesia: 1.0.1
  http: 0.13.5
  dio: 4.0.6
  flutter_html: 3.0.0-alpha.3
  shared_preferences: 2.0.15
  keyboard_dismisser: 2.0.0
  go_router: 3.1.1
  dropdown_search: 3.0.1
  cached_network_image: 3.2.0
  flutter_svg: 1.0.3
  salomon_bottom_bar: 3.3.1
  syncfusion_flutter_calendar: 
  syncfusion_flutter_datagrid: 
  syncfusion_flutter_pdfviewer:
  syncfusion_flutter_sliders:
  advance_pdf_viewer: 2.0.1
  smooth_page_indicator: 1.0.0
  image_picker: 0.8.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/svg/
    - assets/img/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
    
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Regular.ttf
